services:
  mongo:
    image: mongo:latest
    container_name: my_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

